# User Configuration for ${keyboard.name}

# Enable ZMK Studio support for custom shields
CONFIG_ZMK_STUDIO_USB_CDC_ACM=y
CONFIG_ZMK_STUDIO_USB_CONTROL=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
